KeyError: 'links'
172.31.196.16 - - [10/Sep/2024 19:42:21] "POST /load_graph HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/runner/NeuroGraphDynamics/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/NeuroGraphDynamics/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/NeuroGraphDynamics/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/NeuroGraphDynamics/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/NeuroGraphDynamics/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/NeuroGraphDynamics/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/NeuroGraphDynamics/app.py", line 117, in load_graph
    kg.graph = nx.node_link_graph(data)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<class 'networkx.utils.decorators.argmap'> compilation 4", line 3, in argmap_node_link_graph_1
    import gzip
            ^^^
  File "/home/runner/NeuroGraphDynamics/.pythonlibs/lib/python3.11/site-packages/networkx/utils/backends.py", line 633, in __call__
    return self.orig_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/NeuroGraphDynamics/.pythonlibs/lib/python3.11/site-packages/networkx/readwrite/json_graph/node_link.py", line 230, in node_link_graph
    for d in data[link]:
             ^^^^^^^^^^^
KeyError: 'links'